In [ ]:
#Numpy Library >> Numerical python
import numpy as np
np.__version__



'2.0.2'

In [ ]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [ ]:
l=[1,2,3,4,5]
arr=np.array(l)
type(arr) #nd is a n dimensional array

numpy.ndarray

In [ ]:
import numpy as np
l=[1,2,3,4,"Shri"]
arr1=np.array(l)
arr1


array(['1', '2', '3', '4', 'Shri'], dtype='<U21')

In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2
arr2.ndim

2

In [ ]:
mat=np.matrix([1,2,3])
mat.ndim
type(mat)

numpy.matrix

Matrix is a specialized two dimensional array. It only have two dimensions (square brackets opening/closing is the dimension)

In [ ]:
arr3=np.array([[[1,2,3],[4,5,6]]])
arr3.ndim

3

In [ ]:
t = ([1,2,3],[4,5,6])
type(t)

tuple

In [ ]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
l= [1,2,3,4]
arr=np.array(l)
arr

array([1, 2, 3, 4])

In [ ]:
arr[0]=1000
arr

array([1000,    2,    3,    4])

In [ ]:
a=arr  # It is a concept of shallow copy in which a and arr is pointing to the same
# memory location and change in a or arr will reflect in both
a[0]=5000
arr

array([5000,    2,    3,    4])

In [ ]:
b=arr.copy() # It is a concept of deep copy in which the change in b or arr does
# not reflect in other one.
b

array([5000,    2,    3,    4])

In [ ]:
b[0]=3000
b

array([3000,    2,    3,    4])

In [ ]:
arr

array([5000,    2,    3,    4])

In [ ]:
arr4=np.fromfunction(lambda i,j:i==j,(3,3))

In [ ]:
arr4

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
arr4.ndim

2

In [ ]:
arr4.shape

(3, 3)

In [ ]:
arr4.size

9

In [ ]:
arr5=np.fromfunction(lambda i,j:i*j,(3,3))
arr5

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
iterator=(i for i in range(5))
iterator

<generator object <genexpr> at 0x7cf8be930930>

In [ ]:
np.fromiter(iterator,int)

array([0, 1, 2, 3, 4])

In [ ]:
np.fromstring('22 23 24',sep=" ",dtype=int) # by default data type is float

array([22, 23, 24])

In [ ]:
string="Ajay,Bijay,Sanjay"
string.split(",")
string

'Ajay,Bijay,Sanjay'

In [ ]:
np.array(string.split(","))

array(['Ajay', 'Bijay', 'Sanjay'], dtype='<U6')

In [ ]:
np.arange(1,10) # arange gives the specified values

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2) # start,stop,step

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(1,5,10) # Return evenly spaced numbers over a specified interval.

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [ ]:
import numpy as np
arr=np.zeros((1,3,4),dtype=int)
arr

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
arr.ndim

3

In [ ]:
arr.shape

(1, 3, 4)

In [ ]:
arr1 = np.zeros((3,3),dtype=int)
arr1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr1+5 # We can add any element to the array(indexwise) it works as matrix addition

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
arr2=arr1+5
arr2

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
arr2*2


array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
arr2-2 # Similarly we can subtract

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [ ]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.empty((3,4),dtype=int) #Return any random values

array([[56531557,        0,        0,        0],
       [       0,        0,        0,        0],
       [       0,        0,        0,        0]])

There is a random module in python which gives any random value

In [ ]:
import random
random.choice((1,2,3,4,5))

3

In [ ]:
random.choice("Ajay")

'A'

In [ ]:
random.randrange(1,10,2) # Gives any random number between the range specified

7

In [ ]:
random.random() # Returns any random valur from 0(included) and 1(excluded)

0.20603156910068054

In [ ]:
lis=[1,2,3,4,5]
lis

[1, 2, 3, 4, 5]

In [ ]:
random.shuffle(lis)
lis

[5, 2, 3, 1, 4]

In [ ]:
np.random.random_sample()

0.7176889618057131

In [ ]:
np.random.random_sample((5,)) # Gives 5 random values array

array([0.96443909, 0.08432141, 0.09517533, 0.9684238 , 0.50959914])

In [ ]:
np.random.rand(1)

array([0.86173341])

In [ ]:
np.random.rand(2,3)

array([[0.94785684, 0.00646573, 0.45222244],
       [0.62051313, 0.96404464, 0.86923662]])

In [ ]:
np.random.randn(2,3) # Gives array of shape specified in normal distribution()
# normal distribution means in marathi DONGAR shaped

array([[-0.74498004,  1.33913845,  1.2980802 ],
       [-0.2008579 ,  0.43198088,  1.45931612]])

In [ ]:
arr=np.random.randint(1,5,size=(3,4))
arr

array([[2, 3, 1, 3],
       [4, 1, 2, 3],
       [4, 4, 3, 4]])

In [ ]:
import numpy as np
arr=np.random.randint(1,5,size=(3,4))
arr

array([[2, 1, 1, 4],
       [1, 2, 1, 4],
       [4, 3, 2, 3]])

In [ ]:
arr.reshape(2,6) # array size will never change in reshape

array([[2, 1, 1, 4, 1, 2],
       [1, 4, 4, 3, 2, 3]])

In [ ]:
# When we don't know the rows or column number of an array
# use any negative value instead of it.
arr.reshape(4,-1)

array([[2, 1, 1],
       [4, 1, 2],
       [1, 4, 4],
       [3, 2, 3]])

In [ ]:
# base is used to see original array
arr.reshape(4,-1).base

array([[2, 1, 1, 4],
       [1, 2, 1, 4],
       [4, 3, 2, 3]])

In [ ]:
arr.reshape(2,2,3) # for third dimension multiplication should be same

array([[[2, 1, 1],
        [4, 1, 2]],

       [[1, 4, 4],
        [3, 2, 3]]])

In [ ]:
arr.reshape(4,3,1)

array([[[2],
        [1],
        [1]],

       [[4],
        [1],
        [2]],

       [[1],
        [4],
        [4]],

       [[3],
        [2],
        [3]]])

In [ ]:
arr.reshape(1,4,3,1)

array([[[[2],
         [1],
         [1]],

        [[4],
         [1],
         [2]],

        [[1],
         [4],
         [4]],

        [[3],
         [2],
         [3]]]])

In [ ]:
arr1=np.random.randint(1,10,(4,3))
arr1

array([[6, 8, 3],
       [8, 1, 4],
       [7, 5, 4],
       [7, 4, 9]])

In [ ]:
arr1>4

array([[ True,  True, False],
       [ True, False, False],
       [ True,  True, False],
       [ True, False,  True]])

In [ ]:
arr1[arr1>4] # select the all numbers from array where condition is true

array([6, 8, 8, 7, 5, 7, 9])

In [ ]:
# access the elements of an array
arr1[0] # will access the 0th row of an array

array([6, 8, 3])

In [ ]:
# if we want to access the 3 from above row
arr1[0][2]

3

In [ ]:
# if we wnt to access 0th row to 2nd row
# it is similar to the string slicing
arr1[0:3] # because 3 is exclusive

array([[6, 8, 3],
       [8, 1, 4],
       [7, 5, 4]])

In [ ]:
# if we want to access 0th row to 2nd row and also 0th and 2nd cloumn
arr1[0:3,[0,2]]

array([[6, 3],
       [8, 4],
       [7, 4]])

In [ ]:
arr1

array([[6, 8, 3],
       [8, 1, 4],
       [7, 5, 4],
       [7, 4, 9]])

In [ ]:
# operations on an array
import numpy as np
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [ ]:
arr1

array([[1, 1, 1],
       [1, 1, 2],
       [2, 2, 2]])

In [ ]:
arr2

array([[1, 2, 2],
       [2, 1, 2],
       [2, 2, 1]])

In [ ]:
arr1+arr2 #indexwise addition of elements

array([[2, 3, 3],
       [3, 2, 4],
       [4, 4, 3]])

In [ ]:
arr1-arr2

array([[ 0, -1, -1],
       [-1,  0,  0],
       [ 0,  0,  1]])

In [ ]:
arr1*arr2 # it is indexwise multiplication not an array multiplication

array([[1, 2, 2],
       [2, 1, 4],
       [4, 4, 2]])

In [ ]:
arr1,arr2

(array([[1, 1, 1],
        [1, 1, 2],
        [2, 2, 2]]),
 array([[1, 2, 2],
        [2, 1, 2],
        [2, 2, 1]]))

In [ ]:
arr1/arr2

array([[1. , 0.5, 0.5],
       [0.5, 1. , 1. ],
       [1. , 1. , 2. ]])

In [ ]:
arr1/0

<ipython-input-11-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
arr1 @ arr2 # it is matrix multiplication

array([[ 5,  5,  5],
       [ 7,  7,  6],
       [10, 10, 10]])

In [ ]:
np.dot(arr1,arr2) # it is also a way of matrix multiplication

array([[ 5,  5,  5],
       [ 7,  7,  6],
       [10, 10, 10]])

In [ ]:
# Transpose of a matrix is converting rows to columns and columns to rows
arr1

array([[1, 1, 1],
       [1, 1, 2],
       [2, 2, 2]])

In [ ]:
arr1.T

array([[1, 1, 2],
       [1, 1, 2],
       [1, 2, 2]])

In [ ]:
import numpy as np
arr1=np.random.randint(1,4,(3,3))
arr2=np.random.randint(1,4,(3,3))

In [ ]:
arr1

array([[2, 2, 1],
       [3, 1, 2],
       [1, 3, 1]])

In [ ]:
arr2

array([[2, 1, 2],
       [2, 3, 2],
       [3, 2, 1]])

In [ ]:
arr1.flatten() # Converts the given array into one dimensional array

array([2, 2, 1, 3, 1, 2, 1, 3, 1])

In [ ]:
#expand dimension
arr=np.array([1,2,3,4])


In [ ]:
np.expand_dims(arr,axis=0) # axis is used to define rowwise or columnwise expansion
# if it is 0 then rowwise and for 1 it is columnwise expansion will be done

array([[1, 2, 3, 4]])

In [ ]:
arr.ndim

1

In [ ]:
arr1=np.array([[1],[2],[3]])
arr1

array([[1],
       [2],
       [3]])

In [ ]:
arr1.ndim

2

In [ ]:
np.squeeze(arr1).ndim # squeeze reduces the dimension of array by 1

1

In [ ]:
np.repeat(arr1,4) # repeats the given array by specified times

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [ ]:
import numpy as np
arr1=np.random.randint(1,4,(3,3))
arr1

array([[3, 2, 2],
       [2, 3, 3],
       [2, 2, 2]])

In [ ]:
np.repeat(arr1,4,axis=0) # Repeats array row wise

array([[3, 2, 2],
       [3, 2, 2],
       [3, 2, 2],
       [3, 2, 2],
       [2, 3, 3],
       [2, 3, 3],
       [2, 3, 3],
       [2, 3, 3],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
arr1=np.array([[1],[2],[3]])
arr1

array([[1],
       [2],
       [3]])

In [ ]:
np.roll(arr1,-1)

array([[2],
       [3],
       [1]])

In [ ]:
np.roll(arr1,-2)

array([[3],
       [1],
       [2]])

In [ ]:
arr2=np.array(["pw","skills"])
arr2

array(['pw', 'skills'], dtype='<U6')

In [ ]:
np.char.upper(arr2)

array(['PW', 'SKILLS'], dtype='<U6')

In [ ]:
np.char.capitalize(arr2)

array(['Pw', 'Skills'], dtype='<U6')

In [ ]:
arr1

array([[1],
       [2],
       [3]])

In [ ]:
np.sin(arr1)

array([[0.84147098],
       [0.90929743],
       [0.14112001]])

In [ ]:
np.cos(arr1)

array([[ 0.54030231],
       [-0.41614684],
       [-0.9899925 ]])

In [ ]:
np.log10(arr1)

array([[0.        ],
       [0.30103   ],
       [0.47712125]])

In [ ]:
np.max(arr1)

3

In [ ]:
np.min(arr1)

1

In [ ]:
np.mean(arr1)

2.0

In [ ]:
np.std(arr1) #gives standard deviation

0.816496580927726

In [ ]:
np.var(arr1) # gives variance of an array

0.6666666666666666

In [ ]:
np.sqrt(arr1)

array([[1.        ],
       [1.41421356],
       [1.73205081]])

In [ ]:
e=np.array([5,3,7,8,2,1])
np.sort(e)

array([1, 2, 3, 5, 7, 8])

In [ ]:
np.searchsorted(e,9) # gives index of specified number where it should be inserted

6

In [ ]:
np.count_nonzero(e)

6

In [ ]:
np.where(e>0)

(array([0, 1, 2, 3, 4, 5]),)

In [ ]:
e.byteswap()

array([360287970189639680, 216172782113783808, 504403158265495552,
       576460752303423488, 144115188075855872,  72057594037927936])

In [ ]:
import numpy.matlib as nm
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [ ]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
np.full((3,3),'SHRI')

array([['SHRI', 'SHRI', 'SHRI'],
       ['SHRI', 'SHRI', 'SHRI'],
       ['SHRI', 'SHRI', 'SHRI']], dtype='<U4')

In [ ]:
import numpy as np
import pandas as pd
pd.Series([1,2,3,"one"])

0      1
1      2
2      3
3    one
dtype: object